### ISSUE TITLE
Always Cast spells Removeable and Transferrable With Bags

### ISSUE THREAD

**Issue by EveOfTheRoses** [Hupaqa/Bags-Of-Many#2]
In my use of the mod I found that I could shift click or even click and drag on empty areas to pull an always cast off a wand and into a universal bag (have not tested with the spell bag) and it would add one capacity to the wand while giving me the always cast as a spell in the bag. I could then put the always cast on another wand and it would remove one capacity and make it an always cast on that wand.
Dragging a spell onto an empty space on the wand could also cause it to "swap" with the always cast removing it and putting it into the bag aswell. 

This was fine and fun (if overpowered somewhat) except when making the mistake of shift clicking it and having the always cast enter the top spell inventory which causes it to dissapear. Other spells can be put into the place it would occupy in the inventory yet when you have all but one space empty it will then say "Cannot pick up, please drop a spell" as if you have a full inventory. There does not seem to be any way to remove the always cast spell from your spell inventory and I cannot find a way to edit my player file to remove it from there.

**Comment by Hupaqa** [comment]
Damn I never saw your issue! I am fixing this problem at the moment. I think I have found the bug within the code that allowed to move always cast wands.

I might want to add an upgrade or a special bag that permits modifying always cast spells at some point unsure.
